[project]
name = "ex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "pandas>=2.3.3",
    "xlrd>=2.0.2",
    "openpyxl>=3.1.5",
]
